### PR TITLE
Fix test failure from 434684613971

### PR DESCRIPTION
**Pull request by derat**
Specify the click target using the 'css=' syntax rather than a document.querySelector() call.

### CODE REVIEW

**Comment by derat** [comment]
@mwiencek / @reosarevok / @yvanzo, I suspect that this might fix the failure in e.g. https://ci.metabrainz.org/job/musicbrainz-server/11145/console:

```
  [12:59:27.360Z] click target="document.querySelector('#tracklist table.medium tr.track:nth-child(9) td.title input.track-name')" value=""
    ⨯ caught exception: TypeError: webdriver.By[using] is not a function at makeLocator
```

**Review by yvanzo — APPROVED** [review]
Thank you! :motor_boat:
